import {
  Alert,
  Button,
  Card,
  Code,
  ConfirmButton,
  Field,
  Input,
  PageTitle,
} from '@althobe/ui/components';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { api, type Account } from '../api';
import { errorText, ROLE } from '../format';
import { meQuery, usersQuery } from '../queries';

const ROLE_NAMES = Object.keys(ROLE);

/**
 * Owner only (the API enforces admin.users.write). Passwords are generated by the server and
 * shown once, to be handed over in person — never sent by chat or email.
 */
export function UsersPage() {
  const { data: me } = useQuery(meQuery);
  const { data: users = [], isLoading, error } = useQuery(usersQuery);
  const [shown, setShown] = useState<{ email: string; password: string } | null>(null);

  if (error) return <Alert>{errorText(error)}</Alert>;

  return (
    <>
      <PageTitle>المستخدمون</PageTitle>
      {shown && (
        <div className="mb-4">
          <Alert tone="warn">
            كلمة مرور مؤقتة لـ <Code>{shown.email}</Code>: <Code>{shown.password}</Code> — تظهر مرة
            واحدة فقط. سلّمها للشخص مباشرة، وسيغيّرها من «حسابي».{' '}
            <button type="button" className="underline" onClick={() => setShown(null)}>
              إخفاء
            </button>
          </Alert>
        </div>
      )}
      <CreateUser onCreated={setShown} />
      <Card className="mt-4 overflow-x-auto p-0">
        <table className="w-full">
          <thead className="bg-blush text-sm text-ink-muted">
            <tr>
              <th className="p-3 text-start">الاسم</th>
              <th className="p-3 text-start">البريد</th>
              <th className="p-3 text-start">الأدوار</th>
              <th className="p-3 text-start">آخر دخول</th>
              <th className="p-3 text-start" />
            </tr>
          </thead>
          <tbody>
            {users.map((u) => (
              <UserRow key={u.id} user={u} isMe={u.id === me?.id} onPassword={setShown} />
            ))}
            {isLoading && (
              <tr>
                <td colSpan={5} className="p-6 text-center text-ink-muted">
                  جارٍ التحميل…
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </Card>
    </>
  );
}

function RolePicker({ value, onChange }: { value: string[]; onChange: (roles: string[]) => void }) {
  return (
    <div className="flex flex-wrap gap-2">
      {ROLE_NAMES.map((role) => (
        <label
          key={role}
          className="flex items-center gap-1 rounded-lg border border-stone px-2 py-1 text-sm"
        >
          <input
            type="checkbox"
            checked={value.includes(role)}
            onChange={(e) =>
              onChange(e.target.checked ? [...value, role] : value.filter((r) => r !== role))
            }
          />
          {ROLE[role]}
        </label>
      ))}
    </div>
  );
}

function CreateUser({
  onCreated,
}: {
  onCreated: (p: { email: string; password: string }) => void;
}) {
  const [email, setEmail] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [roles, setRoles] = useState<string[]>(['warehouse_keeper']);
  const queryClient = useQueryClient();

  const create = useMutation({
    mutationFn: async () => api.createUser({ email, nameAr, roles }),
    onSuccess: async ({ user, password }) => {
      onCreated({ email: user.email, password });
      setEmail('');
      setNameAr('');
      await queryClient.invalidateQueries({ queryKey: usersQuery.queryKey });
    },
  });

  const submit = (event: FormEvent) => {
    event.preventDefault();
    create.mutate();
  };

  return (
    <Card>
      <form onSubmit={submit} className="flex flex-col gap-3">
        <div className="grid gap-3 md:grid-cols-2">
          <Field label="الاسم">
            <Input required value={nameAr} onChange={(e) => setNameAr(e.target.value)} />
          </Field>
          <Field label="البريد الإلكتروني">
            <Input
              type="email"
              dir="ltr"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </Field>
        </div>
        <Field label="الأدوار">
          <RolePicker value={roles} onChange={setRoles} />
        </Field>
        <div>
          <Button type="submit" disabled={create.isPending || roles.length === 0}>
            إضافة مستخدم
          </Button>
        </div>
        {create.isError && <Alert>{errorText(create.error)}</Alert>}
      </form>
    </Card>
  );
}

function UserRow({
  user,
  isMe,
  onPassword,
}: {
  user: Account;
  isMe: boolean;
  onPassword: (p: { email: string; password: string }) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [roles, setRoles] = useState(user.roles);
  const queryClient = useQueryClient();
  const refresh = async () => queryClient.invalidateQueries({ queryKey: usersQuery.queryKey });

  const update = useMutation({
    mutationFn: async (patch: { roles?: string[]; isActive?: boolean }) =>
      api.updateUser(user.id, patch),
    onSuccess: async () => {
      setEditing(false);
      await refresh();
    },
  });
  const reset = useMutation({
    mutationFn: async () => api.resetPassword(user.id),
    onSuccess: ({ password }) => onPassword({ email: user.email, password }),
  });

  return (
    <tr className={`border-t border-stone ${user.isActive ? '' : 'opacity-50'}`}>
      <td className="p-3 font-medium">
        {user.nameAr} {isMe && <span className="text-sm text-ink-muted">(أنت)</span>}
        {!user.isActive && <span className="text-sm text-bad"> — موقوف</span>}
        {(update.error ?? reset.error) && (
          <div className="text-sm text-bad">{errorText(update.error ?? reset.error)}</div>
        )}
      </td>
      <td className="p-3">
        <Code>{user.email}</Code>
      </td>
      <td className="p-3">
        {editing ? (
          <div className="flex flex-col gap-2">
            <RolePicker value={roles} onChange={setRoles} />
            <div className="flex gap-2">
              <Button
                disabled={roles.length === 0 || update.isPending}
                onClick={() => update.mutate({ roles })}
              >
                حفظ
              </Button>
              <Button variant="ghost" onClick={() => setEditing(false)}>
                رجوع
              </Button>
            </div>
          </div>
        ) : (
          user.roles.map((r) => ROLE[r] ?? r).join('، ')
        )}
      </td>
      <td className="tabular p-3 text-sm text-ink-muted" dir="ltr">
        {user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString('en-GB') : '—'}
      </td>
      <td className="p-2">
        {!editing && (
          <div className="flex flex-wrap justify-end gap-1">
            <Button variant="ghost" onClick={() => setEditing(true)}>
              الأدوار
            </Button>
            {!isMe && (
              <ConfirmButton
                variant="ghost"
                disabled={reset.isPending}
                onConfirm={() => reset.mutate()}
              >
                كلمة مرور جديدة
              </ConfirmButton>
            )}
            {!isMe && (
              <ConfirmButton
                variant={user.isActive ? 'danger' : 'secondary'}
                disabled={update.isPending}
                onConfirm={() => update.mutate({ isActive: !user.isActive })}
              >
                {user.isActive ? 'إيقاف' : 'تفعيل'}
              </ConfirmButton>
            )}
          </div>
        )}
      </td>
    </tr>
  );
}
