import { z } from 'zod';
import { unitCostSchema } from '../../shared/money.js';

export const openScanSessionSchema = z
  .object({
    kind: z.enum(['OPENING', 'RECEIVE', 'TRANSFER', 'DAMAGE']),
    locationId: z.uuid(),
    toLocationId: z.uuid().optional(),
    reason: z.string().trim().min(3).max(500).optional(),
    note: z.string().trim().max(500).optional(),
  })
  .superRefine((s, ctx) => {
    if (s.kind === 'TRANSFER') {
      if (!s.toLocationId) {
        ctx.addIssue({
          code: 'custom',
          path: ['toLocationId'],
          message: 'A transfer needs a destination',
        });
      } else if (s.toLocationId === s.locationId) {
        ctx.addIssue({
          code: 'custom',
          path: ['toLocationId'],
          message: 'Source and destination must differ',
        });
      }
    } else if (s.toLocationId) {
      ctx.addIssue({
        code: 'custom',
        path: ['toLocationId'],
        message: 'Only a transfer has a destination',
      });
    }
    if (s.kind === 'DAMAGE' && !s.reason) {
      ctx.addIssue({ code: 'custom', path: ['reason'], message: 'Damage needs a reason' });
    }
  });

export const scanSchema = z.object({
  sessionId: z.uuid(),
  barcode: z.string().trim().min(1).max(64),
  // Generated by the client for every physical scan; the same scanId twice is one scan.
  scanId: z.string().trim().min(8).max(64),
});

export const setLineQuantitySchema = z.object({
  sessionId: z.uuid(),
  variantId: z.uuid(),
  quantity: z.number().int().min(1).max(1_000_000),
});

export const setLineCostSchema = z.object({
  sessionId: z.uuid(),
  variantId: z.uuid(),
  unitCost: unitCostSchema,
});

export const lineRefSchema = z.object({
  sessionId: z.uuid(),
  variantId: z.uuid(),
});

export const sessionRefSchema = z.object({
  sessionId: z.uuid(),
});

export type OpenScanSessionInput = z.input<typeof openScanSessionSchema>;
export type ScanInput = z.input<typeof scanSchema>;
export type SetLineQuantityInput = z.input<typeof setLineQuantitySchema>;
export type SetLineCostInput = z.input<typeof setLineCostSchema>;
export type LineRef = z.input<typeof lineRefSchema>;
export type SessionRef = z.input<typeof sessionRefSchema>;
